// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingMate.Data.Context;

#nullable disable

namespace ShoppingMate.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ItemsShoppingListsJoint", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("ShoppingListId")
                        .HasColumnType("int");

                    b.HasKey("ItemId", "ShoppingListId");

                    b.HasIndex("ShoppingListId");

                    b.ToTable("ItemsShoppingListsJoint");
                });

            modelBuilder.Entity("ShoppingMate.Core.Model.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(6612),
                            IsActive = true,
                            Name = "Clothes"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(6624),
                            IsActive = true,
                            Name = "Household Appliances"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(6625),
                            IsActive = true,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(6626),
                            IsActive = true,
                            Name = "Furniture"
                        });
                });

            modelBuilder.Entity("ShoppingMate.Core.Model.Concrete.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBought")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(7975),
                            IsActive = true,
                            IsBought = false,
                            ProductId = 1,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(7980),
                            IsActive = true,
                            IsBought = false,
                            ProductId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(7981),
                            IsActive = true,
                            IsBought = false,
                            ProductId = 3,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(7982),
                            IsActive = true,
                            IsBought = false,
                            ProductId = 4,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(7983),
                            IsActive = true,
                            IsBought = false,
                            ProductId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(7984),
                            IsActive = true,
                            IsBought = false,
                            ProductId = 6,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(7985),
                            IsActive = true,
                            IsBought = false,
                            ProductId = 7,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(7986),
                            IsActive = true,
                            IsBought = false,
                            ProductId = 8,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(7987),
                            IsActive = true,
                            IsBought = false,
                            ProductId = 9,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(7988),
                            IsActive = true,
                            IsBought = false,
                            ProductId = 10,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(7989),
                            IsActive = true,
                            IsBought = false,
                            ProductId = 11,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(7990),
                            IsActive = true,
                            IsBought = false,
                            ProductId = 12,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(7991),
                            IsActive = true,
                            IsBought = false,
                            ProductId = 13,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(7991),
                            IsActive = true,
                            IsBought = false,
                            ProductId = 14,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(7992),
                            IsActive = true,
                            IsBought = false,
                            ProductId = 15,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(7993),
                            IsActive = true,
                            IsBought = false,
                            ProductId = 16,
                            Quantity = 5
                        });
                });

            modelBuilder.Entity("ShoppingMate.Core.Model.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("UnitType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(9206),
                            IsActive = true,
                            Name = "Blue Jean",
                            Price = 80m,
                            Stock = 100,
                            UnitType = "piece"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(9210),
                            IsActive = true,
                            Name = "Leather Jacket",
                            Price = 150m,
                            Stock = 100,
                            UnitType = "piece"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(9212),
                            IsActive = true,
                            Name = "Sweetshirt",
                            Price = 60m,
                            Stock = 100,
                            UnitType = "piece"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(9214),
                            IsActive = true,
                            Name = "Dress",
                            Price = 200m,
                            Stock = 100,
                            UnitType = "piece"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(9215),
                            IsActive = true,
                            Name = "Washing Machine",
                            Price = 500m,
                            Stock = 50,
                            UnitType = "piece"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(9216),
                            IsActive = true,
                            Name = "Vacuum Cleaner",
                            Price = 70m,
                            Stock = 50,
                            UnitType = "piece"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(9217),
                            IsActive = true,
                            Name = "Television",
                            Price = 400m,
                            Stock = 50,
                            UnitType = "piece"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(9219),
                            IsActive = true,
                            Name = "Refrigerator",
                            Price = 650m,
                            Stock = 50,
                            UnitType = "piece"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(9220),
                            IsActive = true,
                            Name = "Pasta",
                            Price = 3m,
                            Stock = 250,
                            UnitType = "piece"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(9221),
                            IsActive = true,
                            Name = "Oil",
                            Price = 8m,
                            Stock = 250,
                            UnitType = "piece"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(9223),
                            IsActive = true,
                            Name = "Milk",
                            Price = 5m,
                            Stock = 250,
                            UnitType = "piece"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(9224),
                            IsActive = true,
                            Name = "Bread",
                            Price = 1m,
                            Stock = 250,
                            UnitType = "piece"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(9226),
                            IsActive = true,
                            Name = "Chair",
                            Price = 20m,
                            Stock = 150,
                            UnitType = "piece"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(9228),
                            IsActive = true,
                            Name = "Commode",
                            Price = 30m,
                            Stock = 150,
                            UnitType = "piece"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(9229),
                            IsActive = true,
                            Name = "Seat",
                            Price = 50m,
                            Stock = 150,
                            UnitType = "piece"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 110, DateTimeKind.Local).AddTicks(9230),
                            IsActive = true,
                            Name = "Lampshade",
                            Price = 15m,
                            Stock = 150,
                            UnitType = "piece"
                        });
                });

            modelBuilder.Entity("ShoppingMate.Core.Model.Concrete.ShoppingList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompleteTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalCost")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ShoppingLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 111, DateTimeKind.Local).AddTicks(394),
                            IsActive = true,
                            IsCompleted = false,
                            Name = "Clothes List",
                            TotalCost = 0.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 111, DateTimeKind.Local).AddTicks(397),
                            IsActive = true,
                            IsCompleted = false,
                            Name = "Household Appliances List",
                            TotalCost = 0.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 111, DateTimeKind.Local).AddTicks(398),
                            IsActive = true,
                            IsCompleted = false,
                            Name = "Foods List",
                            TotalCost = 0.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CreateDate = new DateTime(2023, 3, 3, 1, 45, 42, 111, DateTimeKind.Local).AddTicks(399),
                            IsActive = true,
                            IsCompleted = false,
                            Name = "Furnitures List",
                            TotalCost = 0.0
                        });
                });

            modelBuilder.Entity("ItemsShoppingListsJoint", b =>
                {
                    b.HasOne("ShoppingMate.Core.Model.Concrete.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ItemFK");

                    b.HasOne("ShoppingMate.Core.Model.Concrete.ShoppingList", null)
                        .WithMany()
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ShoppingListFK");
                });

            modelBuilder.Entity("ShoppingMate.Core.Model.Concrete.Item", b =>
                {
                    b.HasOne("ShoppingMate.Core.Model.Concrete.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShoppingMate.Core.Model.Concrete.Product", b =>
                {
                    b.HasOne("ShoppingMate.Core.Model.Concrete.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ShoppingMate.Core.Model.Concrete.ShoppingList", b =>
                {
                    b.HasOne("ShoppingMate.Core.Model.Concrete.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ShoppingMate.Core.Model.Concrete.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
